In [2]:
#data load
import pandas as pd

df = pd.read_excel("C:/Users/Nikita/Documents/sales_raw_500.xlsx")
df

     Order_ID           Order_Date Customer Region  Product  Sales   Cost
0        1001            1/13/2023    Rohit  South   Mobile  23289  19118
1        1002  2023-07-10 00:00:00     Aman   West   Laptop   8905   5593
2        1003  2023-05-11 00:00:00    Rahul  South  Monitor  59987  39959
3        1004            2/19/2024    Rahul  South  Printer  49597  33892
4        1005            1/26/2024   Anjali  North   Laptop  54797  34468
..        ...                  ...      ...    ...      ...    ...    ...
515      1389  2024-12-02 00:00:00    Vikas  North   Laptop  17924  12145
516      1496            4/24/2023    Kiran  North  Printer  23434  16388
517      1031            2/19/2023    Vikas   East  Printer  58883  43579
518      1317  2023-05-07 00:00:00     Aman  North   Laptop  76781  66865
519      1409            1/16/2024    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [30]:
#du[licate removes
df = df.drop_duplicates()
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Order_date,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,2023-01-13,4171,2023,1
1,1002,2023-07-10,Aman,West,Laptop,8905,5593,2023-07-10,3312,2023,7
2,1003,2023-05-11,Rahul,South,Monitor,59987,39959,2023-05-11,20028,2023,5
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,2024-02-19,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,2024-01-26,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,2023-10-18,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,2023-04-24,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,2023-06-27,13037,2023,6
480,1498,2023-08-05,Aman,East,Tablet,19160,15636,2023-08-05,3524,2023,8
481,1500,2023-07-10,Vikas,North,Printer,34567,22426,2023-07-10,12141,2023,7

In [25]:
#fix date column
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Order_date,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,2023-01-13,4171,2023,1
1,1002,2023-07-10,Aman,West,Laptop,8905,5593,2023-07-10,3312,2023,7
2,1003,2023-05-11,Rahul,South,Monitor,59987,39959,2023-05-11,20028,2023,5
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,2024-02-19,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,2024-01-26,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,2023-10-18,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,2023-04-24,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,2023-06-27,13037,2023,6
480,1498,2023-08-05,Aman,East,Tablet,19160,15636,2023-08-05,3524,2023,8
481,1500,2023-07-10,Vikas,North,Printer,34567,22426,2023-07-10,12141,2023,7

In [28]:
df = df.dropna(subset=['Order_Date'])
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Order_date,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,2023-01-13,4171,2023,1
1,1002,2023-07-10,Aman,West,Laptop,8905,5593,2023-07-10,3312,2023,7
2,1003,2023-05-11,Rahul,South,Monitor,59987,39959,2023-05-11,20028,2023,5
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,2024-02-19,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,2024-01-26,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,2023-10-18,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,2023-04-24,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,2023-06-27,13037,2023,6
480,1498,2023-08-05,Aman,East,Tablet,19160,15636,2023-08-05,3524,2023,8
481,1500,2023-07-10,Vikas,North,Printer,34567,22426,2023-07-10,12141,2023,7

In [21]:
df['Profit'] = df['Sales']-df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Order_date,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,2023-01-13,4171,2023,1
1,1002,2023-07-10,Aman,West,Laptop,8905,5593,2023-07-10,3312,2023,7
2,1003,2023-05-11,Rahul,South,Monitor,59987,39959,2023-05-11,20028,2023,5
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,2024-02-19,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,2024-01-26,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,2023-10-18,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,2023-04-24,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,2023-06-27,13037,2023,6
497,1498,2023-08-05,Aman,East,Tablet,19160,15636,2023-08-05,3524,2023,8
499,1500,2023-07-10,Vikas,North,Printer,34567,22426,2023-07-10,12141,2023,7

In [22]:
df.to_csv('sales_cleaned.csv', index = False)

In [2]:
#data python + Excel + SQL
import pandas as pd
from sqlalchemy import create_engine

In [19]:
df = pd.read_csv("C:/Users/Nikita/sales_cleaned.csv")
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Order_date,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,2023-01-13,4171,2023,1
1,1002,2023-07-10,Aman,West,Laptop,8905,5593,2023-07-10,3312,2023,7
2,1003,2023-05-11,Rahul,South,Monitor,59987,39959,2023-05-11,20028,2023,5
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,2024-02-19,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,2024-01-26,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,2023-10-18,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,2023-04-24,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,2023-06-27,13037,2023,6
480,1498,2023-08-05,Aman,East,Tablet,19160,15636,2023-08-05,3524,2023,8
481,1500,2023-07-10,Vikas,North,Printer,34567,22426,2023-07-10,12141,2023,7

In [48]:
!pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\nikita\appdata\roaming\python\python313\site-packages (1.1.2)

In [3]:
engine = create_engine('mysql+pymysql://root:Nikita%40254@localhost:3306/salesdb')

In [33]:
# First, check the column names in your DataFrame
print(df.columns)

# Rename one of the duplicate columns
# Option 1: Rename 'Order_date' to something else
df = df.rename(columns={'Order_date': 'Order_date_fixed'})

# OR Option 2: Drop one of the duplicate columns if it's redundant
# df = df.drop(columns=['Order_date'])

# Now try to write to SQL again
df.to_sql(name='sales_data', con=engine, if_exists='replace', index=False)

Index(['Order_ID', 'Order_Date', 'Customer', 'Region', 'Product', 'Sales',
       'Cost', 'Profit', 'Year', 'Month'],
      dtype='object')

482

In [34]:
df.to_sql(name='sales_data',con=engine,if_exists = 'replace', index = False)

482